## This is a sanity check to see if same seed embeddings of NMF are the same

In [1]:
import sys
sys.path.append('../source/')
import numpy as np
from Users import Users
from Producers import *
from embeddings import *
from sklearn.preprocessing import normalize
from plotting import *
from tqdm import tqdm
import pandas as pd

In [2]:
seeds = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29] # seeds for reproducibilit of NMF factorizations
len(seeds)

10

In [ ]:
def arr_of_np_check(arr1, arr2):
  all_bool = []
  for i, val in enumerate(arr1):
    val == arr2[i]

In [18]:
# check for dim 5
dim = 5
em_arr1 = []
for seed in seeds:
  np.random.seed(seed = seed)
  _, nue  = get_user_embeddings_movielens100k(user_dimension =  dim)
  em_arr1.append(nue)

In [19]:
# check for dim 5
dim = 5
em_arr2 = []
for seed in seeds:
  np.random.seed(seed = seed)
  _, nue  = get_user_embeddings_movielens100k(user_dimension =  dim)
  em_arr2.append(nue)

In [14]:
len(em_arr1), em_arr1[0].shape

(10, (943, 5))

In [15]:
np.array(em_arr1).shape

(10, 943, 5)

In [20]:
np.all(np.array(em_arr1) == np.array(em_arr2))

True

In [2]:
dimension, seed, nprod =  10, 11, 10 # NE not found?
np.random.seed(seed = seed)
_, nue  = get_user_embeddings_movielens100k(user_dimension =  dimension)

In [3]:
PEng = ProducersEngagementGame(num_producers = nprod, users = Users(nue), prob = 'linear')
# NE, NE_compact, iters = PEng.best_response_dynamics()

In [4]:
PEng.best_response_dynamics(verbose=True)

##### PRODUCERS FOR ITER 0
 [1. 0. 1. 4. 0. 1. 0. 1. 1. 1.]
##### PRODUCERS FOR ITER 0 
 [1. 0. 1. 3. 0. 1. 1. 1. 1. 1.]
##### PRODUCERS FOR ITER 1 
 [1. 0. 2. 2. 0. 1. 1. 1. 1. 1.]
##### PRODUCERS FOR ITER 2 
 [1. 1. 2. 2. 0. 0. 1. 1. 1. 1.]
##### PRODUCERS FOR ITER 3 
 [1. 1. 2. 2. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 10 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 11 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 12 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 13 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 14 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR 

##### PRODUCERS FOR ITER 159 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 160 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 161 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 162 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 163 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 164 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 165 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 166 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 167 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 168 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 169 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 170 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 171 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 172 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 173 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 174 
 [1. 1. 2. 1. 0. 1. 2. 0.

##### PRODUCERS FOR ITER 296 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 297 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 298 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 299 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 300 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 301 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 302 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 303 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 304 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 305 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 306 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 307 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 308 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 309 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 310 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 311 
 [1. 1. 3. 0. 0. 1. 2. 0.

##### PRODUCERS FOR ITER 459 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 460 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 461 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 462 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 463 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 464 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 465 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 466 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 467 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 468 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 469 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 470 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 471 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 472 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 473 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 474 
 [1. 1. 3. 0. 0. 1. 2. 0.

##### PRODUCERS FOR ITER 590 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 591 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 592 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 593 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 594 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 595 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 596 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 597 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 598 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 599 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 600 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 601 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 602 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 603 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 604 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 605 
 [1. 1. 3. 0. 0. 1. 2. 0.

##### PRODUCERS FOR ITER 772 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 773 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 774 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 775 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 776 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 777 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 778 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 779 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 780 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 781 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 782 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 783 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 784 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 785 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 786 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 787 
 [1. 1. 3. 1. 0. 0. 2. 0.

##### PRODUCERS FOR ITER 918 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 919 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 920 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 921 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 922 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 923 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 924 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 925 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 926 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 927 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 928 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 929 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 930 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 931 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 932 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 933 
 [1. 1. 2. 1. 0. 1. 2. 0.

##### PRODUCERS FOR ITER 1105 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1106 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1107 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1108 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1109 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1110 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1111 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1112 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1113 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1114 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1115 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 1116 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 1117 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1118 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1119 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1120 
 [1. 1. 2

##### PRODUCERS FOR ITER 1281 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1282 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1283 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1284 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1285 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1286 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1287 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1288 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 1289 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 1290 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1291 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1292 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1293 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1294 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1295 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1296 
 [1. 1. 2

##### PRODUCERS FOR ITER 1415 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1416 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1417 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1418 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1419 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1420 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1421 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 1422 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 1423 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1424 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1425 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1426 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 1427 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 1428 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 1429 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1430 
 [1. 1. 3

##### PRODUCERS FOR ITER 1610 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 1611 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1612 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1613 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 1614 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 1615 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 1616 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1617 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1618 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1619 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1620 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1621 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1622 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1623 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1624 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 1625 
 [1. 1. 2

##### PRODUCERS FOR ITER 1794 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1795 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1796 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1797 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1798 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1799 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1800 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1801 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1802 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1803 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1804 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1805 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1806 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1807 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1808 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1809 
 [1. 1. 3

##### PRODUCERS FOR ITER 1954 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1955 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1956 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1957 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1958 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1959 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1960 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1961 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1962 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1963 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1964 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1965 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1966 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1967 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1968 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 1969 
 [1. 1. 3

##### PRODUCERS FOR ITER 2110 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 2111 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 2112 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2113 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2114 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2115 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2116 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2117 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2118 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 2119 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 2120 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 2121 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2122 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2123 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2124 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2125 
 [1. 1. 3

##### PRODUCERS FOR ITER 2253 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 2254 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 2255 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2256 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2257 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2258 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2259 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2260 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2261 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2262 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2263 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2264 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2265 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2266 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2267 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2268 
 [1. 1. 3

##### PRODUCERS FOR ITER 2400 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2401 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2402 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 2403 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 2404 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 2405 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2406 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2407 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 2408 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 2409 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 2410 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2411 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2412 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2413 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2414 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2415 
 [1. 1. 2

##### PRODUCERS FOR ITER 2539 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2540 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2541 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2542 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2543 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2544 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2545 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2546 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2547 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 2548 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 2549 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2550 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2551 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2552 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2553 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2554 
 [1. 1. 3

##### PRODUCERS FOR ITER 2706 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2707 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 2708 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 2709 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2710 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2711 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2712 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2713 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2714 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2715 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2716 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2717 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2718 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2719 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2720 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2721 
 [1. 1. 3

##### PRODUCERS FOR ITER 2873 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2874 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2875 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2876 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2877 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2878 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2879 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2880 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2881 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2882 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2883 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2884 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2885 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2886 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2887 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 2888 
 [1. 1. 3

##### PRODUCERS FOR ITER 3045 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3046 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3047 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3048 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3049 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 3050 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3051 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3052 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3053 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3054 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3055 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3056 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3057 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 3058 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3059 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3060 
 [1. 1. 3

##### PRODUCERS FOR ITER 3223 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3224 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3225 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3226 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3227 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3228 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3229 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3230 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3231 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3232 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3233 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3234 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3235 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 3236 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3237 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3238 
 [1. 1. 3

##### PRODUCERS FOR ITER 3395 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3396 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3397 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3398 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3399 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3400 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3401 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3402 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3403 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3404 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3405 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3406 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3407 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3408 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 3409 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3410 
 [1. 1. 2

##### PRODUCERS FOR ITER 3583 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3584 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3585 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3586 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3587 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3588 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3589 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3590 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 3591 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3592 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3593 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3594 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3595 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 3596 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3597 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3598 
 [1. 1. 3

##### PRODUCERS FOR ITER 3774 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3775 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3776 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 3777 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3778 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3779 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3780 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3781 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 3782 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3783 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3784 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3785 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3786 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 3787 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3788 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 3789 
 [1. 1. 3

##### PRODUCERS FOR ITER 3938 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3939 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3940 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3941 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3942 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3943 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3944 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3945 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3946 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3947 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3948 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3949 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3950 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3951 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3952 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 3953 
 [1. 1. 3

##### PRODUCERS FOR ITER 4104 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4105 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 4106 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4107 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4108 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4109 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4110 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 4111 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4112 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4113 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4114 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4115 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4116 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4117 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4118 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4119 
 [1. 1. 3

##### PRODUCERS FOR ITER 4271 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 4272 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4273 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4274 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4275 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4276 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4277 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4278 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4279 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4280 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4281 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4282 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4283 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4284 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4285 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4286 
 [1. 1. 3

##### PRODUCERS FOR ITER 4409 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4410 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4411 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4412 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4413 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4414 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4415 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4416 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4417 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4418 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4419 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 4420 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4421 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4422 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4423 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4424 
 [1. 1. 3

##### PRODUCERS FOR ITER 4555 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4556 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4557 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4558 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4559 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4560 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4561 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4562 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 4563 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4564 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4565 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4566 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4567 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 4568 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4569 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4570 
 [1. 1. 3

##### PRODUCERS FOR ITER 4743 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4744 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4745 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4746 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4747 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 4748 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4749 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4750 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4751 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4752 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 4753 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4754 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4755 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4756 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4757 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 4758 
 [1. 1. 2

##### PRODUCERS FOR ITER 4897 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4898 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4899 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 4900 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4901 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 4902 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4903 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4904 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4905 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4906 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4907 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4908 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4909 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4910 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4911 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 4912 
 [1. 1. 3

##### PRODUCERS FOR ITER 5058 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5059 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 5060 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 5061 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5062 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5063 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5064 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5065 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5066 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5067 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5068 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5069 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5070 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5071 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5072 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5073 
 [1. 1. 2

##### PRODUCERS FOR ITER 5224 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5225 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 5226 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 5227 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5228 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5229 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5230 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5231 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5232 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5233 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5234 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5235 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5236 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5237 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5238 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5239 
 [1. 1. 2

##### PRODUCERS FOR ITER 5366 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5367 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5368 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 5369 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 5370 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 5371 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5372 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5373 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5374 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5375 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5376 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5377 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5378 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5379 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5380 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5381 
 [1. 1. 3

##### PRODUCERS FOR ITER 5523 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5524 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5525 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5526 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5527 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5528 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5529 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5530 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5531 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5532 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5533 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5534 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5535 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5536 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5537 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5538 
 [1. 1. 3

##### PRODUCERS FOR ITER 5652 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5653 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5654 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5655 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 5656 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 5657 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 5658 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5659 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5660 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5661 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5662 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5663 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5664 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5665 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5666 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5667 
 [1. 1. 3

##### PRODUCERS FOR ITER 5832 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5833 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5834 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5835 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5836 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5837 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5838 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5839 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5840 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5841 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5842 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5843 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5844 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5845 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5846 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5847 
 [1. 1. 3

##### PRODUCERS FOR ITER 5975 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5976 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 5977 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 5978 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 5979 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5980 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5981 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 5982 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 5983 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5984 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5985 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5986 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5987 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5988 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5989 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 5990 
 [1. 1. 3

##### PRODUCERS FOR ITER 6135 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6136 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6137 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6138 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6139 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 6140 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 6141 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6142 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6143 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6144 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6145 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6146 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6147 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6148 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6149 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6150 
 [1. 1. 2

##### PRODUCERS FOR ITER 6318 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 6319 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6320 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6321 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6322 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6323 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6324 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 6325 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 6326 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 6327 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6328 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6329 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6330 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6331 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6332 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6333 
 [1. 1. 3

##### PRODUCERS FOR ITER 6454 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 6455 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 6456 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6457 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6458 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6459 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6460 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6461 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6462 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 6463 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 6464 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 6465 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6466 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6467 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 6468 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 6469 
 [1. 1. 2

##### PRODUCERS FOR ITER 6649 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6650 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6651 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6652 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 6653 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 6654 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 6655 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6656 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6657 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6658 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6659 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6660 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6661 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6662 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6663 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 6664 
 [1. 1. 2

##### PRODUCERS FOR ITER 6806 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6807 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6808 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6809 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6810 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6811 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6812 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6813 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6814 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6815 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6816 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 6817 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 6818 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6819 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6820 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6821 
 [1. 1. 2

##### PRODUCERS FOR ITER 6970 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6971 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6972 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6973 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6974 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6975 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6976 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6977 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6978 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6979 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6980 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6981 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6982 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6983 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6984 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 6985 
 [1. 1. 3

##### PRODUCERS FOR ITER 7126 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7127 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7128 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7129 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7130 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7131 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7132 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7133 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7134 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7135 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 7136 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 7137 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 7138 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7139 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7140 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 7141 
 [1. 1. 2

##### PRODUCERS FOR ITER 7264 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7265 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7266 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7267 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7268 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7269 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7270 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7271 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7272 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7273 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 7274 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 7275 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7276 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7277 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7278 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7279 
 [1. 1. 3

##### PRODUCERS FOR ITER 7413 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 7414 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 7415 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 7416 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7417 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7418 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7419 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7420 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7421 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7422 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7423 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7424 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7425 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7426 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7427 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7428 
 [1. 1. 3

##### PRODUCERS FOR ITER 7595 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7596 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7597 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7598 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7599 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7600 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7601 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7602 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7603 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7604 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7605 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7606 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7607 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7608 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7609 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7610 
 [1. 1. 2

##### PRODUCERS FOR ITER 7773 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7774 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7775 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7776 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 7777 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 7778 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7779 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7780 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7781 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7782 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7783 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7784 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 7785 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 7786 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 7787 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7788 
 [1. 1. 3

##### PRODUCERS FOR ITER 7914 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7915 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7916 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7917 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7918 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7919 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7920 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7921 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7922 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7923 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7924 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7925 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7926 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 7927 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 7928 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 7929 
 [1. 1. 3

##### PRODUCERS FOR ITER 8058 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8059 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8060 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8061 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8062 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8063 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8064 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8065 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8066 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 8067 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 8068 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8069 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8070 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8071 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8072 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8073 
 [1. 1. 3

##### PRODUCERS FOR ITER 8203 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8204 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 8205 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 8206 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 8207 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8208 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8209 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 8210 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 8211 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8212 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8213 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8214 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8215 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8216 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8217 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8218 
 [1. 1. 3

##### PRODUCERS FOR ITER 8338 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8339 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8340 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8341 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8342 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 8343 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 8344 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8345 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8346 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8347 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8348 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8349 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8350 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8351 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8352 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8353 
 [1. 1. 2

##### PRODUCERS FOR ITER 8478 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8479 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 8480 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 8481 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8482 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8483 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8484 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 8485 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 8486 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8487 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8488 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8489 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8490 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8491 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8492 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8493 
 [1. 1. 3

##### PRODUCERS FOR ITER 8621 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 8622 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 8623 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8624 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8625 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8626 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8627 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8628 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8629 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8630 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8631 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8632 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8633 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8634 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 8635 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 8636 
 [1. 1. 2

##### PRODUCERS FOR ITER 8756 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8757 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8758 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8759 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8760 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8761 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8762 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8763 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8764 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 8765 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 8766 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 8767 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8768 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8769 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 8770 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 8771 
 [1. 1. 2

##### PRODUCERS FOR ITER 8904 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8905 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8906 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8907 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8908 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8909 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8910 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8911 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8912 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8913 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8914 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8915 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8916 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8917 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8918 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 8919 
 [1. 1. 2

##### PRODUCERS FOR ITER 9057 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9058 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9059 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9060 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9061 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9062 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9063 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9064 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9065 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9066 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9067 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9068 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9069 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9070 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9071 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9072 
 [1. 1. 3

##### PRODUCERS FOR ITER 9186 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9187 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9188 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9189 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9190 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9191 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 9192 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 9193 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9194 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9195 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9196 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9197 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9198 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9199 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9200 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9201 
 [1. 1. 3

##### PRODUCERS FOR ITER 9348 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9349 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9350 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 9351 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 9352 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9353 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9354 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9355 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9356 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9357 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9358 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 9359 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 9360 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9361 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9362 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9363 
 [1. 1. 2

##### PRODUCERS FOR ITER 9480 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9481 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9482 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9483 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9484 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9485 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9486 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9487 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 9488 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 9489 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9490 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9491 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9492 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9493 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9494 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9495 
 [1. 1. 2

##### PRODUCERS FOR ITER 9626 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9627 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9628 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9629 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9630 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9631 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9632 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9633 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9634 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 9635 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 9636 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 9637 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9638 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9639 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 9640 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 9641 
 [1. 1. 2

##### PRODUCERS FOR ITER 9812 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9813 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9814 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9815 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9816 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 9817 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 9818 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9819 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9820 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9821 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9822 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9823 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9824 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9825 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9826 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9827 
 [1. 1. 3

##### PRODUCERS FOR ITER 9956 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 9957 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9958 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9959 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9960 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 9961 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 9962 
 [1. 1. 2. 1. 0. 0. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 9963 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9964 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9965 
 [1. 1. 3. 0. 0. 1. 2. 1. 0. 1.]
##### PRODUCERS FOR ITER 9966 
 [1. 1. 2. 0. 0. 1. 2. 1. 1. 1.]
##### PRODUCERS FOR ITER 9967 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9968 
 [1. 1. 3. 1. 0. 0. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9969 
 [1. 1. 3. 0. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9970 
 [1. 1. 2. 1. 0. 1. 2. 0. 1. 1.]
##### PRODUCERS FOR ITER 9971 
 [1. 1. 3

(None, None, 9999)

In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [29]:
for run in range(10):
  PEng.best_response_dynamics()

In [30]:
PEng.BR_dyna_NE

set()

In [24]:
NE, NE_compact, iters

(None, None, 9999)

In [9]:
res = [{'NE': , 'iters': 9999}, {'NE': [1,2], 'iters':10}]
df = pd.DataFrame(res)

In [17]:
df['NE']

0      None
1    [1, 2]
Name: NE, dtype: object

In [11]:
df_softmax = pd.read_pickle("../saved_frames/Movielens100k_grid_softmax_statistics.pkl") 

In [12]:
df_softmax['NE_exists'].unique()

array([ True])

In [13]:
df_softmax.iloc[140]

dimension                                                              10
seed                                                                   11
nprod                                                                  10
NE_exists                                                            True
iters                                                                   9
last_profile_compact    [0.0, 0.0, 7.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, ...
producer_dist           [0.0, 0.0, 0.7, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, ...
user_dist               [0.10075397500621953, 0.1004768313800366, 0.10...
total_prod_util                                                 98.947515
avg_prod_util                                                    9.894752
max_prod_util                                                    9.896707
min_prod_util                                                    9.890189
total_user_util                                                 98.947515
avg_user_util                         

In [14]:
df_softmax.iloc[307]

dimension                                                              20
seed                                                                    2
nprod                                                                  80
NE_exists                                                            True
iters                                                                  76
last_profile_compact    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
producer_dist           [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
user_dist               [0.04892099746639292, 0.049776781602278594, 0....
total_prod_util                                                 49.931973
avg_prod_util                                                     0.62415
max_prod_util                                                    0.624162
min_prod_util                                                     0.62409
total_user_util                                                 49.931973
avg_user_util                         

In [8]:
df_linear = pd.read_pickle("../saved_frames/Movielens100k_grid_linear_statistics.pkl") 
df_linear['NE_exists'].unique()

array([ True, False])

In [9]:
from collections import Counter
Counter(df_linear['NE_exists'])

Counter({True: 398, False: 2})

In [ ]:
df_linear

In [10]:
df_linear[df_linear['NE_exists']==False]

dimension  seed  nprod  NE_exists  iters  \
140         10    11     10      False   9999   
307         20     2     80      False   9999   

                                  last_profile_compact  \
140  [1.0, 1.0, 3.0, 1.0, 0.0, 0.0, 2.0, 0.0, 1.0, ...   
307  [0.0, 2.0, 4.0, 7.0, 10.0, 6.0, 0.0, 0.0, 1.0,...   

                                         producer_dist  \
140  [0.1, 0.1, 0.3, 0.1, 0.0, 0.0, 0.2, 0.0, 0.1, ...   
307  [0.0, 0.025, 0.05, 0.0875, 0.125, 0.075, 0.0, ...   

                                             user_dist  total_prod_util  \
140  [0.10075397500621953, 0.1004768313800366, 0.10...             -1.0   
307  [0.04892099746639292, 0.049776781602278594, 0....             -1.0   

     avg_prod_util  max_prod_util  min_prod_util  total_user_util  \
140           -1.0           -1.0           -1.0             -1.0   
307           -1.0           -1.0           -1.0             -1.0   

     avg_user_util  max_user_util  min_user_util  
140           -1.0           -1.0           -1.0  
307           -1.0           -1.0           -1.0

In [27]:
df[df['NE_exists'] == True]

dimension  seed  nprod  NE_exists  iters  \
0           5     2     10       True      2   
1           5     2     20       True      9   
2           5    11     10       True      8   
3           5    11     20       True      6   
4           5    13     10       True      4   
5           5    13     20       True      6   
6          10     2     10       True      6   
7          10     2     20       True      8   
9          10    11     20       True      9   
10         10    13     10       True      5   
11         10    13     20       True     11   

                                 last_profile_compact  \
0                           [0.0, 1.0, 2.0, 4.0, 3.0]   
1                           [0.0, 2.0, 5.0, 7.0, 6.0]   
2                           [4.0, 0.0, 1.0, 4.0, 1.0]   
3                           [7.0, 0.0, 3.0, 8.0, 2.0]   
4                           [2.0, 2.0, 3.0, 3.0, 0.0]   
5                           [3.0, 4.0, 6.0, 7.0, 0.0]   
6   [1.0, 1.0, 2.0, 0.0, 2.0, 0.0, 1.0, 1.0, 1.0, ...   
7   [2.0, 2.0, 5.0, 1.0, 3.0, 1.0, 1.0, 1.0, 2.0, ...   
9   [2.0, 2.0, 5.0, 1.0, 1.0, 1.0, 4.0, 1.0, 1.0, ...   
10  [2.0, 2.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, ...   
11  [4.0, 3.0, 0.0, 1.0, 2.0, 2.0, 3.0, 1.0, 2.0, ...   

                                        producer_dist  \
0                           [0.0, 0.1, 0.2, 0.4, 0.3]   
1                         [0.0, 0.1, 0.25, 0.35, 0.3]   
2                           [0.4, 0.0, 0.1, 0.4, 0.1]   
3                         [0.35, 0.0, 0.15, 0.4, 0.1]   
4                           [0.2, 0.2, 0.3, 0.3, 0.0]   
5                         [0.15, 0.2, 0.3, 0.35, 0.0]   
6   [0.1, 0.1, 0.2, 0.0, 0.2, 0.0, 0.1, 0.1, 0.1, ...   
7   [0.1, 0.1, 0.25, 0.05, 0.15, 0.05, 0.05, 0.05,...   
9   [0.1, 0.1, 0.25, 0.05, 0.05, 0.05, 0.2, 0.05, ...   
10  [0.2, 0.2, 0.0, 0.1, 0.1, 0.1, 0.1, 0.0, 0.1, ...   
11  [0.2, 0.15, 0.0, 0.05, 0.1, 0.1, 0.15, 0.05, 0...   

                                            user_dist  total_prod_util  \
0   [0.19337245991569033, 0.19468834366168863, 0.2...       218.761486   
1   [0.19337245991569033, 0.19468834366168863, 0.2...       219.111221   
2   [0.2069150374759016, 0.19162830538328504, 0.19...       219.340249   
3   [0.2069150374759016, 0.19162830538328504, 0.19...       219.773827   
4   [0.19679261082752314, 0.19919425851274117, 0.2...       219.363784   
5   [0.19679261082752314, 0.19919425851274117, 0.2...       219.175223   
6   [0.099439880688442, 0.10023135992812268, 0.104...       119.386177   
7   [0.099439880688442, 0.10023135992812268, 0.104...       119.744957   
9   [0.10075397500621953, 0.1004768313800366, 0.10...       119.511974   
10  [0.10216890934201826, 0.10320454153778091, 0.0...       119.342973   
11  [0.10216890934201826, 0.10320454153778091, 0.0...       119.615333   

    avg_prod_util  max_prod_util  min_prod_util  total_user_util  \
0       21.876149      22.425543      21.578272       218.761486   
1       10.955561      10.976965      10.893951       219.111221   
2       21.934025      22.704814      21.812450       219.340249   
3       10.988691      11.083346      10.896310       219.773827   
4       21.936378      22.128051      21.569679       219.363784   
5       10.958761      11.018493      10.887467       219.175223   
6       11.938618      12.167271      11.691142       119.386177   
7        5.987248       6.129474       5.934632       119.744957   
9        5.975599       6.072429       5.924313       119.511974   
10      11.934297      12.314939      11.734360       119.342973   
11       5.980767       6.041146       5.926182       119.615333   

    avg_user_util  max_user_util  min_user_util  
0        0.231985       0.546305       0.129731  
1        0.232355       0.577060       0.135115  
2        0.232598       0.633087       0.124636  
3        0.233058       0.625218       0.130986  
4        0.232623       0.480046       0.163672  
5        0.232423       0.487005       0.156964  
6

In [17]:
df_NEexists = df_linear[df_linear['NE_exists']]

dimension  seed  nprod  NE_exists  iters  \
0            5     2     10       True      2   
1            5     2     20       True      9   
2            5     2     30       True     17   
3            5     2     40       True     14   
4            5     2     50       True     21   
..         ...   ...    ...        ...    ...   
395         20    29     60       True     42   
396         20    29     70       True     44   
397         20    29     80       True     45   
398         20    29     90       True     60   
399         20    29    100       True     71   

                                  last_profile_compact  \
0                            [0.0, 1.0, 2.0, 4.0, 3.0]   
1                            [0.0, 2.0, 5.0, 7.0, 6.0]   
2                           [0.0, 2.0, 8.0, 11.0, 9.0]   
3                         [1.0, 3.0, 10.0, 14.0, 12.0]   
4                         [1.0, 4.0, 13.0, 17.0, 15.0]   
..                                                 ...   
395  [8.0, 3.0, 0.0, 2.0, 6.0, 11.0, 0.0, 0.0, 9.0,...   
396  [9.0, 3.0, 0.0, 2.0, 7.0, 13.0, 0.0, 0.0, 10.0...   
397  [11.0, 4.0, 0.0, 2.0, 8.0, 14.0, 0.0, 0.0, 12....   
398  [12.0, 4.0, 0.0, 3.0, 9.0, 16.0, 0.0, 0.0, 14....   
399  [13.0, 5.0, 0.0, 3.0, 10.0, 18.0, 0.0, 0.0, 15...   

                                         producer_dist  \
0                            [0.0, 0.1, 0.2, 0.4, 0.3]   
1                          [0.0, 0.1, 0.25, 0.35, 0.3]   
2    [0.0, 0.06666666666666667, 0.26666666666666666...   
3                      [0.025, 0.075, 0.25, 0.35, 0.3]   
4                        [0.02, 0.08, 0.26, 0.34, 0.3]   
..                                                 ...   
395  [0.13333333333333333, 0.05, 0.0, 0.03333333333...   
396  [0.12857142857142856, 0.04285714285714286, 0.0...   
397  [0.1375, 0.05, 0.0, 0.025, 0.1, 0.175, 0.0, 0....   
398  [0.13333333333333333, 0.044444444444444446, 0....   
399  [0.13, 0.05, 0.0, 0.03, 0.1, 0.18, 0.0, 0.0, 0...   

                                             user_dist  total_prod_util  \
0    [0.19337245991569033, 0.19468834366168863, 0.2...       218.761486   
1    [0.19337245991569033, 0.19468834366168863, 0.2...       219.111221   
2    [0.19337245991569033, 0.19468834366168863, 0.2...       218.839327   
3    [0.19337245991569033, 0.19468834366168863, 0.2...       219.165683   
4    [0.19337245991569033, 0.19468834366168863, 0.2...       219.197235   
..                                                 ...              ...   
395  [0.051694889981336097, 0.04983736989270799, 0....        66.243926   
396  [0.051694889981336097, 0.04983736989270799, 0....        66.245144   
397  [0.051694889981336097, 0.04983736989270799, 0....        66.233007   
398  [0.051694889981336097, 0.04983736989270799, 0....        66.271831   
399  [0.051694889981336097, 0.04983736989270799, 0....        66.251551   

     avg_prod_util  max_prod_util  min_prod_util  total_user_util  \
0        21.876149      22.425543      21.578272       218.761486   
1        10.955561      10.976965      10.893951       219.111221   
2         7.294644       7.380982       7.278639       218.839327   
3         5.479142       5.493348       5.466450       219.165683   
4         4.383945       4.401370       4.372016       219.197235   
..             ...            ...            ...              ...   
395       1.104065       1.112531       1.097684        66.243926   
396       0.946359       0.951403       0.942138        66.245144   
397       0.827913       0.837436       0.823844        66.233007   
398       0.736354       0.738314       0.732955        66.271831   
399       0.662516       0.665569       0.660819        66.251551   

     avg_user_util  max_user_util  min_user_util  
0         0.231985       0.546305       0.129731  
1         0.232355       0.577060       0.135115  
2         0.232067       0.581999       0.133271  
3         0.232413       0.577520       0.161502  
4         0.232447       0.584844    

In [20]:
utils_columns = ['total_prod_util','avg_prod_util', 'max_prod_util', 'min_prod_util', 'total_user_util','avg_user_util',\
'max_user_util', 'min_user_util']

In [23]:
df_softmax_utils = df_softmax[df_linear['NE_exists']][utils_columns]

In [24]:
df_linear_utils  = df_linear[df_linear['NE_exists']][utils_columns]

In [28]:
(df_linear_utils > df_softmax_utils)

total_prod_util  avg_prod_util  max_prod_util  min_prod_util  \
0               True           True           True           True   
1               True           True           True           True   
2               True           True           True           True   
3               True           True           True           True   
4               True           True           True           True   
..               ...            ...            ...            ...   
395             True           True           True           True   
396             True           True           True           True   
397             True           True           True           True   
398             True           True           True           True   
399             True           True           True           True   

     total_user_util  avg_user_util  max_user_util  min_user_util  
0               True           True           True           True  
1               True           True           True           True  
2               True           True           True           True  
3               True           True           True           True  
4               True           True           True           True  
..               ...            ...            ...            ...  
395             True           True          False           True  
396             True           True          False           True  
397             True           True          False           True  
398             True           True          False           True  
399             True           True          False           True  

[398 rows x 8 columns]

In [26]:
(df_linear_utils > df_softmax_utils).describe()

total_prod_util avg_prod_util max_prod_util min_prod_util  \
count              398           398           398           398   
unique               1             1             1             1   
top               True          True          True          True   
freq               398           398           398           398   

       total_user_util avg_user_util max_user_util min_user_util  
count              398           398           398           398  
unique               1             1             2             1  
top               True          True          True          True  
freq               398           398           237           398

In [27]:
(df_linear_utils > df_softmax_utils).sum(axis=0)

total_prod_util    398
avg_prod_util      398
max_prod_util      398
min_prod_util      398
total_user_util    398
avg_user_util      398
max_user_util      237
min_user_util      398
dtype: int64

In [30]:
import pickle
with open('../saved_frames/user_emb_norm_l2_32.pkl', 'rb') as file1:         
    ue = pickle.load(file1)

In [34]:
ue.shape

(6040, 32)

In [38]:
np.max(ue), np.min(ue)

(0.6027592, -0.5767613)

In [44]:
np.mean(np.abs(ue), axis=0)

array([0.12566069, 0.15141028, 0.24139573, 0.16480206, 0.08736598,
       0.19432104, 0.133552  , 0.0960379 , 0.12056502, 0.23159029,
       0.17015122, 0.1378867 , 0.17309617, 0.11195485, 0.10659129,
       0.18135254, 0.12851724, 0.15819947, 0.1678278 , 0.1513337 ,
       0.12141249, 0.08830423, 0.15440436, 0.1242734 , 0.18331586,
       0.11855268, 0.09489657, 0.2530378 , 0.09793954, 0.1542472 ,
       0.15744936, 0.08548304], dtype=float32)

In [ ]:
plt.plot(np.arange())

In [40]:
np.linalg.norm(ue[0])

1.0