In [1]:
import sys
sys.path.append('../source/')
import numpy as np
from Users import Users
from Producers import *
from embeddings import *
from sklearn.preprocessing import normalize

In [2]:
# EXPERIMENT 1 - Exposure objective on Movielens data
dimension = 5
num_producers = 100
num_users = 943
seed = 17

np.random.seed(seed)

user_embeddings = generate_uniform_users(dimension = dimension, num_users = num_users)
users = Users(user_embeddings)
PEng = ProducerLinearExposureGame(num_producers=num_producers, users=users)

In [ ]:
converged, lp, lp_compact, iters = PEng.best_response_dynamics(verbose=True)

##### PRODUCERS FOR ITER 0
 [18. 23. 16. 16. 27.]


/home/jupyter-kriach/.conda/envs/recsys/lib/python3.10/site-packages/cvxpy/problems/problem.py:158: UserWarning: Objective contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn("Objective contains too many subexpressions. "
/home/jupyter-kriach/.conda/envs/recsys/lib/python3.10/site-packages/cvxpy/reductions/solvers/solving_chain.py:336: FutureWarning: 
    Your problem is being solved with the ECOS solver by default. Starting in 
    CVXPY 1.5.0, Clarabel will be used as the default solver instead. To continue 
    using ECOS, specify the ECOS solver explicitly using the ``solver=cp.ECOS`` 
    argument to the ``problem.solve`` method.
    
  warnings.warn(ECOS_DEPRECATION_MSG, FutureWarning)


##### PRODUCERS FOR ITER 0 
 [19. 23. 16. 16. 26.]
##### PRODUCERS FOR ITER 1 
 [20. 22. 16. 16. 26.]
##### PRODUCERS FOR ITER 2 
 [20.93492393 22.         16.00000007 16.         25.065076  ]
##### PRODUCERS FOR ITER 3 
 [21.56033199 22.         16.13568513 15.         25.30398288]
##### PRODUCERS FOR ITER 4 
 [21.8772606  22.         16.20401677 15.00000001 24.91872262]
##### PRODUCERS FOR ITER 5 
 [22.0828172  22.         16.2838458  14.34088298 25.29245402]
##### PRODUCERS FOR ITER 6 
 [22.18679081 22.         15.81800985 14.51359194 25.4816074 ]
##### PRODUCERS FOR ITER 7 
 [21.73338886 22.         16.08893246 14.60077936 25.57689932]
##### PRODUCERS FOR ITER 8 
 [22.01010884 22.         16.22575884 14.64464365 25.11948866]
##### PRODUCERS FOR ITER 9 
 [22.15016707 22.         15.78856406 14.66694079 25.39432809]
##### PRODUCERS FOR ITER 10 
 [22.34362828 21.         16.17801273 14.79685641 25.68150257]
##### PRODUCERS FOR ITER 11 
 [22.44164995 21.00000001 16.37544181 14.35600729