In [1]:
import sys
sys.path.append('../source/')
import numpy as np
from Users import Users
from Producers import *
from embeddings import *
from sklearn.preprocessing import normalize

In [23]:
# EXPERIMENT 1 - Exposure with linear serving utility, run best response dynamics twice, takes long
dimension = 5
num_producers = 100
num_users = 100
seed = 17

np.random.seed(seed)

user_embeddings = generate_uniform_users(dimension = dimension, num_users = num_users)
users = Users(user_embeddings)
PExp = ProducerLinearExposureGame(num_producers=num_producers, users=users, epsilon = 1e-2) # epsilon for the epsilon-NE
converged_exp, lp_exp, lp_compact_exp, iters_exp = PExp.best_response_dynamics(verbose=True) # FIRST RUN

##### PRODUCERS FOR ITER 0
 [22. 16. 22. 18. 22.]


/home/jupyter-kriach/.conda/envs/recsys/lib/python3.10/site-packages/cvxpy/reductions/solvers/solving_chain.py:336: FutureWarning: 
    Your problem is being solved with the ECOS solver by default. Starting in 
    CVXPY 1.5.0, Clarabel will be used as the default solver instead. To continue 
    using ECOS, specify the ECOS solver explicitly using the ``solver=cp.ECOS`` 
    argument to the ``problem.solve`` method.
    
  warnings.warn(ECOS_DEPRECATION_MSG, FutureWarning)


##### PRODUCERS FOR ITER 0 
 [22. 16. 23. 18. 21.]
##### PRODUCERS FOR ITER 1 
 [22. 16. 24. 17. 21.]
##### PRODUCERS FOR ITER 2 
 [21. 16. 25. 17. 21.]
##### PRODUCERS FOR ITER 3 
 [21.         16.         25.99999999 16.         21.        ]
##### PRODUCERS FOR ITER 4 
 [21.00000002 16.00000001 26.99999997 16.         20.        ]
##### PRODUCERS FOR ITER 5 
 [21.16374116 16.09867367 27.73758517 16.         19.        ]
##### PRODUCERS FOR ITER 6 
 [21.4604475  16.25412837 28.28542412 15.         19.        ]
##### PRODUCERS FOR ITER 7 
 [21.80875374 16.49884975 28.69239651 15.         18.        ]
##### PRODUCERS FOR ITER 8 
 [22.18423734 16.79013548 29.02562718 15.         17.        ]
##### PRODUCERS FOR ITER 9 
 [22.57453697 17.10647048 29.31899254 15.         16.        ]
##### PRODUCERS FOR ITER 10 
 [22.9734353  17.43702106 29.58954364 15.00000001 15.        ]
##### PRODUCERS FOR ITER 11 
 [23.38945298 17.7108173  29.89972971 14.00000001 15.        ]
##### PRODUCERS FOR ITER 1

In [24]:
print(converged_exp, lp_compact_exp, iters_exp)

True [27.17642967 20.5769198  32.24997542 11.9966751   8.00000002] 22


In [26]:
# SECOND RUN OF best response dynamics
converged_exp, lp_exp, lp_compact_exp, iters_exp = PExp.best_response_dynamics(verbose=True)
# lp_compact has the sum of producer strategies across dimensions

##### PRODUCERS FOR ITER 0
 [16. 24. 22. 17. 21.]
##### PRODUCERS FOR ITER 0 
 [16.56726354 24.         22.43273646 17.         20.        ]
##### PRODUCERS FOR ITER 1 
 [17.10363403 24.         22.89636597 16.         20.        ]
##### PRODUCERS FOR ITER 2 
 [17.63578216 24.         23.36421784 16.         19.        ]
##### PRODUCERS FOR ITER 3 
 [18.15542417 24.         23.84457583 15.         19.        ]
##### PRODUCERS FOR ITER 4 
 [18.68127839 24.         24.31872161 15.         18.        ]
##### PRODUCERS FOR ITER 5 
 [19.21212826 24.         24.78787174 15.         17.        ]
##### PRODUCERS FOR ITER 6 
 [19.74740473 24.         25.25259527 15.         16.        ]
##### PRODUCERS FOR ITER 7 
 [20.2705822  24.         25.72941779 14.         16.        ]
##### PRODUCERS FOR ITER 8 
 [20.73937871 23.         26.26062129 14.         16.        ]
##### PRODUCERS FOR ITER 9 
 [21.18005002 22.         26.81994997 14.         16.        ]
##### PRODUCERS FOR ITER 10 
 [21.657349

In [27]:
print(converged_exp, lp_compact_exp, iters_exp) # lp_compact has the sum of producer strategies across dimensions

True [27.17568682 20.58245358 32.24519337 11.99666621  8.00000001] 24


In [28]:
PExp.BR_dyna_epsNE

{(27.175686824684487,
  20.582453579273203,
  32.24519337133185,
  11.996666209716233,
  8.000000014630363),
 (27.17642967057992,
  20.57691979777521,
  32.2499754181421,
  11.99667509800908,
  8.000000015117873)}

In [30]:
for s in PExp.BR_dyna_epsNE: # this set saves all the epsilon - nash equilibria
    print(np.sum(s))

99.9999999996242
99.99999999963615


In [31]:
# EXPERIMENT - compare with engagement utility, Way faster
dimension = 5
num_producers = 100
num_users = 100
seed = 17

np.random.seed(seed)

user_embeddings = generate_uniform_users(dimension = dimension, num_users = num_users)
users = Users(user_embeddings)
PEng = ProducersEngagementGame(num_producers=num_producers, users=users)
converged_eng, lp_eng, lp_compact_eng, iters_eng = PEng.best_response_dynamics(verbose=True)

##### PRODUCERS FOR ITER 0
 [22. 16. 22. 18. 22.]
##### PRODUCERS FOR ITER 0 
 [22. 17. 22. 18. 21.]
##### PRODUCERS FOR ITER 1 
 [22. 17. 23. 17. 21.]
##### PRODUCERS FOR ITER 2 
 [21. 18. 23. 17. 21.]
##### PRODUCERS FOR ITER 3 
 [21. 18. 24. 16. 21.]
##### PRODUCERS FOR ITER 4 
 [21. 19. 24. 16. 20.]
##### PRODUCERS FOR ITER 5 
 [21. 19. 25. 16. 19.]
##### PRODUCERS FOR ITER 6 
 [21. 19. 26. 15. 19.]
##### PRODUCERS FOR ITER 7 
 [21. 20. 26. 15. 18.]
##### PRODUCERS FOR ITER 8 
 [20. 20. 27. 15. 18.]
##### PRODUCERS FOR ITER 9 
 [21. 20. 27. 15. 17.]
##### PRODUCERS FOR ITER 10 
 [21. 21. 27. 15. 16.]
##### PRODUCERS FOR ITER 11 
 [21. 21. 28. 14. 16.]
##### PRODUCERS FOR ITER 12 
 [22. 21. 28. 14. 15.]
##### PRODUCERS FOR ITER 13 
 [22. 22. 28. 13. 15.]
##### PRODUCERS FOR ITER 14 
 [22. 22. 29. 13. 14.]
##### PRODUCERS FOR ITER 15 
 [23. 22. 29. 12. 14.]
##### PRODUCERS FOR ITER 16 
 [23. 23. 29. 12. 13.]
##### PRODUCERS FOR ITER 17 
 [24. 23. 29. 11. 13.]
##### PRODUCERS FOR ITER

In [32]:
# user utilities with producers maximizing for exposure
dir_prod, prod_utils, user_utils = get_all_engagement_utilities(lp_exp, user_embeddings)
np.min(user_utils), np.mean(user_utils)

(0.20604382158558798, 0.31073405791948105)

In [33]:
# user utilities with producers maximizing for engagement
dir_prod, prod_utils, user_utils = get_all_engagement_utilities(lp_eng, user_embeddings)
np.min(user_utils), np.mean(user_utils)

(0.18933588534488874, 0.33091175967801073)

In [36]:
lp_compact_exp, lp_compact_eng # exposure vs engagement weights across dimensions

(array([27.17568682, 20.58245358, 32.24519337, 11.99666621,  8.00000001]),
 array([27., 25., 32., 11.,  5.]))

In [11]:
user_embeddings.sum(axis=0)

array([21.03172959, 19.9761332 , 22.12108909, 18.93840249, 17.93264563])