In [138]:
import sys
sys.path.append('../source/')
import numpy as np
from Users import Users
from Producers import ProducersEngagementGame
from embeddings import generate_uniform_user
from sklearn.preprocessing import normalize

Workflow is:
1) Create User object
2) Create ProducersEngagementGame
3) Run Producer dynamics

In [120]:
# EXPERIMENT 1 - Linear probability of RS
dimension = 5
num_users = 10
num_producers = 4

user_embeddings = np.array([generate_uniform_user(dimension) for _ in range(num_users)])
users = Users(user_embeddings)
PEng = ProducersEngagementGame(num_producers=num_producers, users=users, prob = 'linear')

In [121]:
user_embeddings

array([[0.38039438, 0.15948064, 0.13651518, 0.21781202, 0.10579778],
       [0.0030275 , 0.40543198, 0.07617561, 0.32280799, 0.19255693],
       [0.11200457, 0.25205085, 0.22526089, 0.34465915, 0.06602453],
       [0.18815378, 0.08958091, 0.34189536, 0.34684001, 0.03352993],
       [0.14783737, 0.3841454 , 0.21132332, 0.23004451, 0.02664941],
       [0.40295531, 0.34892141, 0.0015875 , 0.13855925, 0.10797653],
       [0.76364291, 0.01331703, 0.11568377, 0.06523019, 0.04212611],
       [0.02814075, 0.12851489, 0.14391109, 0.06068714, 0.63874612],
       [0.25657492, 0.02320765, 0.09262316, 0.1509646 , 0.47662966],
       [0.01772002, 0.12654479, 0.43756097, 0.22268329, 0.19549094]])

In [133]:
PEng.best_response_dynamics(verbose=True)

##### PRODUCERS FOR ITER 0
 [[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
##### PRODUCERS FOR ITER 0 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]
##### PRODUCERS FOR ITER 1 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
##### PRODUCERS FOR ITER 2 
 [[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
##### PRODUCERS FOR ITER 3 
 [[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]
Number of iterations to coverge: 3


(array([2., 0., 0., 1., 1.]), 3)

In [134]:
PEng.BR_dyna_NE

{(2.0, 0.0, 0.0, 1.0, 1.0)}

In [135]:
PEng.brute_force_NEsearch()

{(2.0, 0.0, 0.0, 1.0, 1.0)}

In [136]:
PEng.BruteForce_NE

{(2.0, 0.0, 0.0, 1.0, 1.0)}

In [15]:
NE, NE.sum()

(array([2., 1., 2.]), 5.0)

In [11]:
# EXPERIMENT 2 - Softmax probability of RS
dimension = 15
num_users = 1000
num_producers = 100

user_embeddings = np.array([generate_uniform_user(dimension) for _ in range(num_users)])
users = Users(user_embeddings)
PEng = ProducersEngagementGame(num_producers=num_producers, users=users, prob = 'softmax')
NE, iters= PEng.best_response_dynamics(verbose=False)

In [12]:
NE, NE.sum()

(array([ 0.,  3.,  0.,  0., 11.,  0.,  0.,  7.,  9.,  0., 25., 45.,  0.,
         0.,  0.]),
 100.0)

In [175]:
# Experiment - 3, user embeddings sorted, softmax probability
num_users = 1000
dimension = 15
num_producers = 100
feature_weights = np.sort(generate_uniform_user(dimension))
unweighted_array = np.array([generate_uniform_user(dimension) for i in range(num_users)])
user_embeddings = normalize(np.multiply(feature_weights,unweighted_array),"l1")

In [176]:
user_embeddings.sum(axis=0), user_embeddings.shape

(array([  9.72655803,  10.87518798,  20.85154254,  21.33576737,
         29.85898003,  41.6220864 ,  48.88586949,  61.82964795,
         65.58215433,  91.53915927,  95.07188414, 100.5710156 ,
        107.2685074 , 112.10764588, 182.87399358]),
 (1000, 15))

In [177]:
runs = 10

In [178]:
users = Users(user_embeddings)
PEng = ProducersEngagementGame(num_producers=num_producers, users=users, prob = 'linear')
for run in range(runs):
    PEng.best_response_dynamics(verbose=False) # runs a single best response dynamics
NE_linear = PEng.BR_dyna_NE

In [179]:
users = Users(user_embeddings)
PEng = ProducersEngagementGame(num_producers=num_producers, users=users, prob = 'softmax')
for run in range(runs):
    PEng.best_response_dynamics(verbose=False) # runs a single best response dynamics
NE_softmax = PEng.BR_dyna_NE

In [180]:
print(NE_linear)
print(NE_softmax)

{(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 5.0, 8.0, 9.0, 76.0)}
{(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 100.0)}


In [154]:
PEng.BR_dyna_NE

{(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 100.0)}