In [19]:
import sys
sys.path.append('../source/')
import numpy as np
from Users import Users
from Producers import ProducersEngagementGame
from embeddings import generate_uniform_user
from sklearn.preprocessing import normalize
from surprise import NMF
from surprise import Dataset
from surprise.model_selection import cross_validate
from sklearn.preprocessing import normalize
import numpy as np
import random
from tqdm import tqdm

### Synthetic data uniformly drawn


In [39]:
num_users = 10000
dimensions = [5, 10, 15]
num_producers = 100
runs = 10 # number of BRD runs for each game

#### Dimension = 5, linear and softmax

In [5]:
# for dim = 5
dim = 5
user_embeddings = np.array([generate_uniform_user(dim) for i in range(num_users)])

In [13]:
print(user_embeddings.shape)
print(np.sum(user_embeddings, axis=1), np.max(user_embeddings), np.min(user_embeddings))
np.mean(user_embeddings, axis=0), np.std(user_embeddings, axis=0)

(10000, 5)
[1. 1. 1. ... 1. 1. 1.] 0.9311126606742359 1.2388563260246066e-05


(array([0.19885719, 0.20164988, 0.20212607, 0.20155954, 0.19580732]),
 array([0.16292697, 0.16392367, 0.16354044, 0.16389205, 0.1614871 ]))

#### LINEAR, d=5

In [40]:
users = Users(user_embeddings)
PEng = ProducersEngagementGame(num_producers=num_producers, users=users, prob = 'softmax') #change back to linear
for run in tqdm(range(runs)):
    PEng.best_response_dynamics(verbose=False) # runs a single best response dynamics
NE_linear_uniform_users = PEng.BR_dyna_NE

100%|██████████| 10/10 [00:55<00:00,  5.59s/it]


In [41]:
print(f'#unique nash equilibria {len(NE_linear_uniform_users)}', NE_linear_uniform_users)

#unique nash equilibria 1 {(17.0, 24.0, 26.0, 24.0, 9.0)}


In [31]:
tuple_producer_profile = NE_linear_uniform_users.pop()
print(tuple_producer_profile)

(19.0, 21.0, 21.0, 21.0, 18.0)


In [42]:
tuple_producer_profile = NE_linear_uniform_users.pop()
print(tuple_producer_profile)
NE_softmax_dim5 = np.array(tuple_producer_profile)

(17.0, 24.0, 26.0, 24.0, 9.0)


In [34]:
NE_linear_dim5 = np.array(tuple_producer_profile)

In [44]:
NE_linear_dim5, NE_softmax_dim5

(array([19., 21., 21., 21., 18.]), array([17., 24., 26., 24.,  9.]))

In [46]:
np.sum(user_embeddings, axis=0) / np.sum(user_embeddings), np.sum(user_embeddings, axis=0) / user_embeddings.shape[0]

(array([0.19885719, 0.20164988, 0.20212607, 0.20155954, 0.19580732]),
 array([0.19885719, 0.20164988, 0.20212607, 0.20155954, 0.19580732]))