In [1]:
import sys
sys.path.append('../source/')
import numpy as np
from Users import Users
from Producers import *
from embeddings import *
from sklearn.preprocessing import normalize
from plotting import *
from tqdm import tqdm
import pandas as pd

In [2]:
seeds = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29] # seeds for reproducibilit of NMF factorizations
len(seeds)

10

In [3]:
dimension, seed, nprod =  5, 11, 5 # NE not found?
n_users = 10
np.random.seed(seed = seed)
# _, nue  = get_user_embeddings_movielens100k(user_dimension =  dimension)
nue = generate_uniform_users(dimension = dimension, num_users = n_users)
PEng = ProducersEngagementGame(num_producers = nprod, users = Users(nue), prob = 'softmax')

In [4]:
# PEng = ProducersEngagementGame(num_producers = nprod, users = Users(nue), prob = 'linear')
# # NE, NE_compact, iters = PEng.best_response_dynamics()

In [5]:
# PEng.best_response_dynamics(verbose=True)

In [6]:
PEng = ProducersEngagementGame(num_producers = nprod, users = Users(nue), prob = 'softmax', temp = 0.01)

In [7]:
converged, last_profile, last_profile_compact, iters  = PEng.best_response_dynamics(verbose=True)

##### PRODUCERS FOR ITER 0
 [0. 2. 1. 2. 0.]
##### PRODUCERS FOR ITER 0 
 [0. 1. 1. 2. 1.]
##### PRODUCERS FOR ITER 1 
 [0. 1. 2. 1. 1.]
##### PRODUCERS FOR ITER 2 
 [0. 2. 2. 0. 1.]
##### PRODUCERS FOR ITER 3 
 [0. 2. 2. 0. 1.]
Number of iterations to coverge: 3


In [8]:
# PEng = ProducersEngagementGame(num_producers = nprod, users = Users(nue), prob = 'softmax', temp = 1)
# PEng.best_response_dynamics(verbose=True)

In [9]:
last_profile.shape

(5, 5)

In [10]:
nue.shape

(10, 5)

In [11]:
get_all_engagement_utilities(last_profile, nue, prob_type='softmax', temp = 0.01)

(array([2, 1, 2, 1, 4]),
 array([0.85335149, 0.71728398, 0.85335149, 0.71728398, 1.24721749]),
 array([0.28148836, 0.51262272, 0.6212284 , 0.4672474 , 0.68363269,
        0.4143551 , 0.48788216, 0.3460028 , 0.1156471 , 0.4583817 ]))