In [1]:
import sys
sys.path.append('../source/')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from Producers import *
from Users import *
from embeddings import *

In [3]:
# testing out on synthetic data

dimension = 5
num_users = 10000
num_producers = 100

user_embeddings = np.array([generate_uniform_user(dimension) for _ in range(num_users)])
users = Users(user_embeddings)
Psmexp = ProducerSoftmaxExposureGame(num_producers=num_producers, users=users)

In [ ]:
PEng = ProducersEngagementGame(num_producers=num_producers, users=users, pr)

In [8]:
converged, lp, lp_compact, i  = Psmexp.best_response_dynamics(verbose=True)

##### PRODUCERS FOR ITER 0
 [17. 19. 23. 17. 24.]
##### PRODUCERS FOR ITER 0 
 [17. 20. 22. 17. 24.]
##### PRODUCERS FOR ITER 1 
 [17. 21. 22. 17. 23.]
##### PRODUCERS FOR ITER 2 
 [17. 21. 21. 17. 24.]
##### PRODUCERS FOR ITER 3 
 [17. 22. 20. 17. 24.]
##### PRODUCERS FOR ITER 4 
 [17. 22. 19. 17. 25.]
##### PRODUCERS FOR ITER 5 
 [17. 23. 18. 17. 25.]
##### PRODUCERS FOR ITER 6 
 [17. 23. 18. 16. 26.]
##### PRODUCERS FOR ITER 7 
 [16. 24. 18. 16. 26.]
##### PRODUCERS FOR ITER 8 
 [15. 24. 18. 16. 27.]
##### PRODUCERS FOR ITER 9 
 [15. 25. 17. 16. 27.]
##### PRODUCERS FOR ITER 10 
 [15. 25. 17. 15. 28.]
##### PRODUCERS FOR ITER 11 
 [16. 25. 16. 15. 28.]
##### PRODUCERS FOR ITER 12 
 [16. 26. 15. 15. 28.]
##### PRODUCERS FOR ITER 13 
 [16. 26. 14. 15. 29.]
##### PRODUCERS FOR ITER 14 
 [16. 26. 14. 15. 29.]
Number of iterations to coverge: 14


In [9]:
Psmexp.BR_dyna_NE

{(16.0, 26.0, 14.0, 15.0, 29.0)}