In [1]:
import sys
sys.path.append('../source/')
import numpy as np
from Users import Users
from Producers import ProducersEngagementGame
from embeddings import generate_uniform_users
from sklearn.preprocessing import normalize

In [2]:
from Producers import *

In [4]:
# EXPERIMENT 1 - Linear probability of RS
dimension = 5
num_users = 10
num_producers = 4

user_embeddings = generate_uniform_users(dimension = dimension, num_users=num_users)
users = Users(user_embeddings)
PEng = ProducersEngagementGame(num_producers=num_producers, users=users, prob = 'linear')
NE, NE_compact, iters = PEng.best_response_dynamics(verbose=True)

##### PRODUCERS FOR ITER 0
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
##### PRODUCERS FOR ITER 0 
 [[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
##### PRODUCERS FOR ITER 1 
 [[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
##### PRODUCERS FOR ITER 2 
 [[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
##### PRODUCERS FOR ITER 3 
 [[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
Number of iterations to coverge: 3


In [5]:
NE, NE_compact

(array([[0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.]]),
 array([2., 0., 0., 0., 2.]))

In [6]:
dir_prod, utils_prod, utils_users = get_all_engagement_utilities(NE, user_embeddings)

In [7]:
dir_prod, utils_prod

(array([4, 4, 0, 0]), array([0.96545875, 0.96545875, 0.79417971, 0.79417971]))

In [8]:
utils_users

array([0.38556769, 0.2738863 , 0.46312451, 0.34529366, 0.18423299,
       0.70957449, 0.27648798, 0.21460999, 0.45402938, 0.21246992])