In [1]:
import sys
sys.path.append('../source/')
import numpy as np
from Users import Users
from Producers import *
from embeddings import *
from sklearn.preprocessing import normalize
from plotting import *
from tqdm import tqdm
import pandas as pd

In [2]:
seeds = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29] # seeds for reproducibilit of NMF factorizations
len(seeds)

10

In [3]:
dimension, seed, nprod =  5, 11, 5 # NE not found?
n_users = 10
np.random.seed(seed = seed)
# _, nue  = get_user_embeddings_movielens100k(user_dimension =  dimension)
nue = generate_uniform_users(dimension = dimension, num_users = n_users)
PEng = ProducersEngagementGame(num_producers = nprod, users = Users(nue), prob = 'softmax')

In [4]:
# PEng = ProducersEngagementGame(num_producers = nprod, users = Users(nue), prob = 'linear')
# # NE, NE_compact, iters = PEng.best_response_dynamics()

In [5]:
# PEng.best_response_dynamics(verbose=True)

In [6]:
PEng = ProducersEngagementGame(num_producers = nprod, users = Users(nue), prob = 'softmax', temp = 0.01)

In [7]:
converged, last_profile, last_profile_compact, iters  = PEng.best_response_dynamics(verbose=True)

##### PRODUCERS FOR ITER 0
 [0. 2. 1. 2. 0.]
##### PRODUCERS FOR ITER 0 
 [0. 1. 1. 2. 1.]
##### PRODUCERS FOR ITER 1 
 [0. 1. 2. 1. 1.]
##### PRODUCERS FOR ITER 2 
 [0. 2. 2. 0. 1.]
##### PRODUCERS FOR ITER 3 
 [0. 2. 2. 0. 1.]
Number of iterations to coverge: 3


In [8]:
# PEng = ProducersEngagementGame(num_producers = nprod, users = Users(nue), prob = 'softmax', temp = 1)
# PEng.best_response_dynamics(verbose=True)

In [9]:
last_profile.shape

(5, 5)

In [10]:
nue.shape

(10, 5)

In [11]:
get_all_engagement_utilities(last_profile, nue, prob_type='softmax', temp = 0.01)

(array([2, 1, 2, 1, 4]),
 array([0.85335149, 0.71728398, 0.85335149, 0.71728398, 1.24721749]),
 array([0.28148836, 0.51262272, 0.6212284 , 0.4672474 , 0.68363269,
        0.4143551 , 0.48788216, 0.3460028 , 0.1156471 , 0.4583817 ]))

In [ ]:
#checks if both frames are same or not for greedy

In [10]:
import pandas as pd

df1 = pd.read_pickle('../saved_frames/synth-uniform_softmax_temp_0.01.pkl')
df2 = pd.read_pickle('../saved_frames/uniform_synthetic_grid_greedy_statistics.pkl')

In [2]:
df1.shape

(400, 16)

In [4]:
df2.shape

(400, 16)

In [6]:
df1

dimension  seed  nprod  NE_exists  iters  \
0            5     2     10       True      3   
1            5     2     20       True      6   
2            5     2     30       True      5   
3            5     2     40       True      4   
4            5     2     50       True      8   
..         ...   ...    ...        ...    ...   
395         20    29     60       True     18   
396         20    29     70       True     18   
397         20    29     80       True     23   
398         20    29     90       True     20   
399         20    29    100       True     34   

                                  last_profile_compact  \
0                            [2.0, 2.0, 2.0, 2.0, 2.0]   
1                            [4.0, 4.0, 4.0, 4.0, 4.0]   
2                            [6.0, 6.0, 6.0, 6.0, 6.0]   
3                            [8.0, 8.0, 8.0, 8.0, 8.0]   
4                       [10.0, 10.0, 10.0, 10.0, 10.0]   
..                                                 ...   
395  [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, ...   
396  [4.0, 4.0, 4.0, 3.0, 4.0, 3.0, 3.0, 3.0, 3.0, ...   
397  [4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, ...   
398  [5.0, 5.0, 5.0, 4.0, 5.0, 4.0, 4.0, 4.0, 4.0, ...   
399  [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...   

                                         producer_dist  \
0                            [0.2, 0.2, 0.2, 0.2, 0.2]   
1                            [0.2, 0.2, 0.2, 0.2, 0.2]   
2                            [0.2, 0.2, 0.2, 0.2, 0.2]   
3                            [0.2, 0.2, 0.2, 0.2, 0.2]   
4                            [0.2, 0.2, 0.2, 0.2, 0.2]   
..                                                 ...   
395  [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.0...   
396  [0.05714285714285714, 0.05714285714285714, 0.0...   
397  [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.0...   
398  [0.05555555555555555, 0.05555555555555555, 0.0...   
399  [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.0...   

                                             user_dist  total_prod_util  \
0    [0.1985065740914945, 0.20296485834765995, 0.19...      4580.160712   
1    [0.1985065740914945, 0.20296485834765995, 0.19...      4580.160712   
2    [0.1985065740914945, 0.20296485834765995, 0.19...      4580.160712   
3    [0.1985065740914945, 0.20296485834765995, 0.19...      4580.160712   
4    [0.1985065740914945, 0.20296485834765995, 0.19...      4580.160712   
..                                                 ...              ...   
395  [0.050078133785279026, 0.049848806809137, 0.05...      1783.017244   
396  [0.050078133785279026, 0.049848806809137, 0.05...      1782.808603   
397  [0.050078133785279026, 0.049848806809137, 0.05...      1783.017244   
398  [0.050078133785279026, 0.049848806809137, 0.05...      1782.891248   
399  [0.050078133785279026, 0.049848806809137, 0.05...      1783.017244   

     avg_prod_util  max_prod_util  min_prod_util  total_user_util  \
0       458.016071     471.101240     439.573110      4580.160712   
1       229.008036     235.550620     219.786555      4580.160712   
2       152.672024     157.033747     146.524370      4580.160712   
3       114.504018     117.775310     109.893278      4580.160712   
4        91.603214      94.220248      87.914622      4580.160712   
..             ...            ...            ...              ...   
395      29.716954      31.586607      27.408338      1783.017244   
396      25.468694      28.825547      22.740216      1782.808603   
397      22.287716      23.689955      20.556253      1783.017244   
398      19.809903      21.732055      18.105236      1782.891248   
399      17.830172      18.951964      16.445003      1783.017244   

     avg_user_util  max_user_util  min_user_util  
0         0.458016       0.957918       0.216822  
1         0.458016       0.957918       0.216822  
2         0.458016       0.957918       0.216822  
3         0.458016       0.957918       0.216822  
4         0.458016       0.957918    

In [9]:
df2.equals(df1), df1.equals(df2)

(True, True)

In [12]:
# df3 = pd.read_pickle('../saved_frames/synth-skewed_softmax_temp_1.0.pkl')
df3.shape

(12, 16)