In [1]:
import sys
sys.path.append('../source/')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_smexp = pd.read_pickle("../saved_frames/Movielens100k_grid_smexposure.pkl") 

In [3]:
df_smexp

dimension  seed  nprod  NE_exists  iters  \
0           5     2     10       True      4   
1           5     2     20       True     11   
2           5    11     10       True      8   
3           5    11     20       True     10   
4           5    13     10       True      6   
5           5    13     20       True     13   
6          10     2     10       True      8   
7          10     2     20       True     19   
8          10    11     10       True      9   
9          10    11     20       True     17   
10         10    13     10       True      8   
11         10    13     20       True     19   

                                 last_profile_compact  \
0                           [0.0, 0.0, 0.0, 6.0, 4.0]   
1                          [0.0, 0.0, 2.0, 11.0, 7.0]   
2                           [5.0, 0.0, 0.0, 5.0, 0.0]   
3                          [9.0, 0.0, 0.0, 11.0, 0.0]   
4                           [0.0, 0.0, 4.0, 6.0, 0.0]   
5                          [0.0, 0.0, 9.0, 11.0, 0.0]   
6   [0.0, 0.0, 8.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, ...   
7   [0.0, 0.0, 16.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0,...   
8   [0.0, 0.0, 7.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, ...   
9   [0.0, 0.0, 14.0, 0.0, 0.0, 0.0, 6.0, 0.0, 0.0,...   
10  [2.0, 7.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...   
11  [5.0, 12.0, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0,...   

                                        producer_dist  \
0                           [0.0, 0.0, 0.0, 0.6, 0.4]   
1                         [0.0, 0.0, 0.1, 0.55, 0.35]   
2                           [0.5, 0.0, 0.0, 0.5, 0.0]   
3                         [0.45, 0.0, 0.0, 0.55, 0.0]   
4                           [0.0, 0.0, 0.4, 0.6, 0.0]   
5                         [0.0, 0.0, 0.45, 0.55, 0.0]   
6   [0.0, 0.0, 0.8, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, ...   
7   [0.0, 0.0, 0.8, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, ...   
8   [0.0, 0.0, 0.7, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, ...   
9   [0.0, 0.0, 0.7, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, ...   
10  [0.2, 0.7, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, ...   
11  [0.25, 0.6, 0.0, 0.0, 0.0, 0.0, 0.15, 0.0, 0.0...   

                                            user_dist  total_prod_util  \
0   [0.19337245991569033, 0.19468834366168863, 0.2...            943.0   
1   [0.19337245991569033, 0.19468834366168863, 0.2...            943.0   
2   [0.2069150374759016, 0.19162830538328504, 0.19...            943.0   
3   [0.2069150374759016, 0.19162830538328504, 0.19...            943.0   
4   [0.19679261082752314, 0.19919425851274117, 0.2...            943.0   
5   [0.19679261082752314, 0.19919425851274117, 0.2...            943.0   
6   [0.099439880688442, 0.10023135992812268, 0.104...            943.0   
7   [0.099439880688442, 0.10023135992812268, 0.104...            943.0   
8   [0.10075397500621953, 0.1004768313800366, 0.10...            943.0   
9   [0.10075397500621953, 0.1004768313800366, 0.10...            943.0   
10  [0.10216890934201826, 0.10320454153778091, 0.0...            943.0   
11  [0.10216890934201826, 0.10320454153778091, 0.0...            943.0   

    avg_prod_util  max_prod_util  min_prod_util  total_user_util  \
0           94.30      94.314148      94.290568       197.233200   
1           47.15      47.155461      47.145713       197.638861   
2           94.30      94.329658      94.270342       199.596804   
3           47.15      47.156282      47.144861       199.579703   
4           94.30      94.331524      94.278984       197.068548   
5           47.15      47.155261      47.143570       197.131149   
6           94.30      94.302663      94.299334        98.928201   
7           47.15      47.151332      47.149667        98.928201   
8           94.30      94.303918      94.298321        98.947515   
9           47.15      47.151959      47.149160        98.947515   
10          94.30      94.329240      94.287927        98.276138   
11          47.15      47.150174      47.149480        98.428433   

    avg_user_util  max_user_util  min_user_util

In [3]:
df_smexp

dimension  seed  nprod  NE_exists  iters  \
0           5     2     10       True      4   
1           5     2     20       True     11   
2           5    11     10       True      8   
3           5    11     20       True     10   
4           5    13     10       True      6   
5           5    13     20       True     13   
6          10     2     10       True      8   
7          10     2     20       True     19   
8          10    11     10       True      9   
9          10    11     20       True     17   
10         10    13     10       True      8   
11         10    13     20       True     19   

                                 last_profile_compact  \
0                           [0.0, 0.0, 0.0, 6.0, 4.0]   
1                          [0.0, 0.0, 2.0, 11.0, 7.0]   
2                           [5.0, 0.0, 0.0, 5.0, 0.0]   
3                          [9.0, 0.0, 0.0, 11.0, 0.0]   
4                           [0.0, 0.0, 4.0, 6.0, 0.0]   
5                          [0.0, 0.0, 9.0, 11.0, 0.0]   
6   [0.0, 0.0, 8.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, ...   
7   [0.0, 0.0, 16.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0,...   
8   [0.0, 0.0, 7.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0, ...   
9   [0.0, 0.0, 14.0, 0.0, 0.0, 0.0, 6.0, 0.0, 0.0,...   
10  [2.0, 7.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...   
11  [5.0, 12.0, 0.0, 0.0, 0.0, 0.0, 3.0, 0.0, 0.0,...   

                                        producer_dist  \
0                           [0.0, 0.0, 0.0, 0.6, 0.4]   
1                         [0.0, 0.0, 0.1, 0.55, 0.35]   
2                           [0.5, 0.0, 0.0, 0.5, 0.0]   
3                         [0.45, 0.0, 0.0, 0.55, 0.0]   
4                           [0.0, 0.0, 0.4, 0.6, 0.0]   
5                         [0.0, 0.0, 0.45, 0.55, 0.0]   
6   [0.0, 0.0, 0.8, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, ...   
7   [0.0, 0.0, 0.8, 0.0, 0.2, 0.0, 0.0, 0.0, 0.0, ...   
8   [0.0, 0.0, 0.7, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, ...   
9   [0.0, 0.0, 0.7, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, ...   
10  [0.2, 0.7, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, ...   
11  [0.25, 0.6, 0.0, 0.0, 0.0, 0.0, 0.15, 0.0, 0.0...   

                                            user_dist  total_prod_util  \
0   [0.19337245991569033, 0.19468834366168863, 0.2...       197.233200   
1   [0.19337245991569033, 0.19468834366168863, 0.2...       197.638861   
2   [0.2069150374759016, 0.19162830538328504, 0.19...       199.596804   
3   [0.2069150374759016, 0.19162830538328504, 0.19...       199.579703   
4   [0.19679261082752314, 0.19919425851274117, 0.2...       197.068548   
5   [0.19679261082752314, 0.19919425851274117, 0.2...       197.131149   
6   [0.099439880688442, 0.10023135992812268, 0.104...        98.928201   
7   [0.099439880688442, 0.10023135992812268, 0.104...        98.928201   
8   [0.10075397500621953, 0.1004768313800366, 0.10...        98.947515   
9   [0.10075397500621953, 0.1004768313800366, 0.10...        98.947515   
10  [0.10216890934201826, 0.10320454153778091, 0.0...        98.276138   
11  [0.10216890934201826, 0.10320454153778091, 0.0...        98.428433   

    avg_prod_util  max_prod_util  min_prod_util  total_user_util  \
0       19.723320      19.744140      19.709440       197.233200   
1        9.881943       9.900954       9.874711       197.638861   
2       19.959680      19.995962      19.923398       199.596804   
3        9.978985       9.987014       9.972416       199.579703   
4       19.706855      19.749435      19.678468       197.068548   
5        9.856557       9.861436       9.850594       197.131149   
6        9.892820       9.893297       9.890914        98.928201   
7        4.946410       4.946648       4.945457        98.928201   
8        9.894752       9.896707       9.890189        98.947515   
9        4.947376       4.948354       4.945094        98.947515   
10       9.827614       9.870703       9.809777        98.276138   
11       4.921422       4.926235       4.918784        98.428433   

    avg_user_util  max_user_util  min_user_util

In [2]:
from Producers import *
from Users import *
from embeddings import *

In [3]:
# testing out on synthetic data

dimension = 5
num_users = 10000
num_producers = 100

user_embeddings = np.array([generate_uniform_user(dimension) for _ in range(num_users)])
users = Users(user_embeddings)
Psmexp = ProducerSoftmaxExposureGame(num_producers=num_producers, users=users)

In [14]:
PEng = ProducersEngagementGame(num_producers=num_producers, users=users, prob='softmax')
PEng.best_response_dynamics(verbose=True)

##### PRODUCERS FOR ITER 0
 [20. 17. 16. 27. 20.]
##### PRODUCERS FOR ITER 0 
 [19. 18. 16. 27. 20.]
##### PRODUCERS FOR ITER 1 
 [19. 18. 15. 27. 21.]
##### PRODUCERS FOR ITER 2 
 [19. 19. 15. 26. 21.]
##### PRODUCERS FOR ITER 3 
 [19. 19. 15. 25. 22.]
##### PRODUCERS FOR ITER 4 
 [18. 20. 15. 25. 22.]
##### PRODUCERS FOR ITER 5 
 [18. 20. 15. 24. 23.]
##### PRODUCERS FOR ITER 6 
 [17. 21. 15. 24. 23.]
##### PRODUCERS FOR ITER 7 
 [17. 21. 15. 23. 24.]
##### PRODUCERS FOR ITER 8 
 [16. 22. 15. 23. 24.]
##### PRODUCERS FOR ITER 9 
 [16. 22. 15. 22. 25.]
##### PRODUCERS FOR ITER 10 
 [16. 23. 14. 22. 25.]
##### PRODUCERS FOR ITER 11 
 [16. 23. 14. 21. 26.]
##### PRODUCERS FOR ITER 12 
 [16. 24. 14. 20. 26.]
##### PRODUCERS FOR ITER 13 
 [15. 24. 14. 20. 27.]
##### PRODUCERS FOR ITER 14 
 [15. 25. 13. 20. 27.]
##### PRODUCERS FOR ITER 15 
 [15. 25. 13. 19. 28.]
##### PRODUCERS FOR ITER 16 
 [16. 25. 13. 18. 28.]
##### PRODUCERS FOR ITER 17 
 [16. 25. 14. 17. 28.]
##### PRODUCERS FOR ITER

(True,
 array([[0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
   

In [8]:
converged, lp, lp_compact, i  = Psmexp.best_response_dynamics(verbose=True)

##### PRODUCERS FOR ITER 0
 [17. 19. 23. 17. 24.]
##### PRODUCERS FOR ITER 0 
 [17. 20. 22. 17. 24.]
##### PRODUCERS FOR ITER 1 
 [17. 21. 22. 17. 23.]
##### PRODUCERS FOR ITER 2 
 [17. 21. 21. 17. 24.]
##### PRODUCERS FOR ITER 3 
 [17. 22. 20. 17. 24.]
##### PRODUCERS FOR ITER 4 
 [17. 22. 19. 17. 25.]
##### PRODUCERS FOR ITER 5 
 [17. 23. 18. 17. 25.]
##### PRODUCERS FOR ITER 6 
 [17. 23. 18. 16. 26.]
##### PRODUCERS FOR ITER 7 
 [16. 24. 18. 16. 26.]
##### PRODUCERS FOR ITER 8 
 [15. 24. 18. 16. 27.]
##### PRODUCERS FOR ITER 9 
 [15. 25. 17. 16. 27.]
##### PRODUCERS FOR ITER 10 
 [15. 25. 17. 15. 28.]
##### PRODUCERS FOR ITER 11 
 [16. 25. 16. 15. 28.]
##### PRODUCERS FOR ITER 12 
 [16. 26. 15. 15. 28.]
##### PRODUCERS FOR ITER 13 
 [16. 26. 14. 15. 29.]
##### PRODUCERS FOR ITER 14 
 [16. 26. 14. 15. 29.]
Number of iterations to coverge: 14


In [9]:
Psmexp.BR_dyna_NE

{(16.0, 26.0, 14.0, 15.0, 29.0)}